### ISSUE TITLE
Wont work with updated qb-input

### ISSUE THREAD

**Issue by alexanderbodnar** [Enzo-DC/qb-bossmenu#2]
Society money section is broken. After submitting the amount i want to deposit/withdrawn it wont work. Only the mouse cursor will appear and its bugged. Need to restart the qb-input to unbug it.

**Comment by Enzo-DC** [comment]
Isnt qb-bossmenu problem, u can find fix here:

https://github.com/qbcore-framework/qb-input/pull/9/files

**Comment by alexanderbodnar** [comment]
Yep now it works. Problem solved
